// file system

//readfile e data ta print hte ,ready hte time lagbe taii console.log("finished...") first e print hye jabe ...time lagb bole node js console.log ke block krbe nah ...thats why node.js called as non-blocking .......but console ke pore print korate chaile sync use krte hbe
const fs = require('fs');

// fs.readFile('pathmodule.js', 'utf-8', (err , data)=>{
//     console.log(err,data)
// })
const a =fs.readFileSync('pathmodule.js'); //by using sync nodejs block console.log("")
console.log(a.toString()) //nahole const a er bute ta print hbe 



// fs.writeFile("writefile.js" , "this is a file generated by writeFile" , ()=>{
//     console.log("writeFile.js is created")
// });


b =fs.writeFileSync("writeSyncfile.js" , "this is a file generated by writeFileSync")
// console.log(b)
console.log("writeSyncFile.js is created")




console.log("finished reading and writing file")